version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1973
      POSTGRES_DB: goodDealsList
    ports:
      - '5432:5432'
#     networks:
#       - postgres_network
# networks:
#       - postgres_network



# version: '3'
# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: mysecretpassword
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/mydb?schema=public"
#     depends_on:
#       - postgres

# volumes:
#   postgres-data:
