import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "./components/Footer";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="display: flex flex-col min-h-dvh">
        <Header />
        <main className="flex-grow main-container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
